import { Archivo_Black } from "next/font/google";
import "./globals.css";

const geistSans = Archivo_Black({
weight:"400",
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
