import { Poppins } from "next/font/google";
import "./globals.css";

import Header from "./Componenets/Fixed/Header/Header";
import Footer from "./Componenets/Fixed/Footer";

const geistSans = Poppins({
weight:["400","500","600","700","800"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable}  antialiased`}
      >
        
        
        <div>

            <Header></Header>

        </div>
        {children}  

        <div>

            <Footer></Footer>


        </div>
      </body>
    </html>
  );
}
